//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel.Repository
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KandCEntities : DbContext
    {
        public KandCEntities()
            : base("name=KandCEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<taxonomy> taxonomies { get; set; }
        public virtual DbSet<project_stage> project_stage { get; set; }
        public virtual DbSet<client_involvement> client_involvement { get; set; }
        public virtual DbSet<external_3rd_party> external_3rd_party { get; set; }
        public virtual DbSet<client_engagement> client_engagement { get; set; }
        public virtual DbSet<end_product> end_product { get; set; }
        public virtual DbSet<perdiem> perdiems { get; set; }
        public virtual DbSet<staffing> staffings { get; set; }
        public virtual DbSet<team_role> team_role { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<initiative_type> initiative_type { get; set; }
        public virtual DbSet<notification> notifications { get; set; }
        public virtual DbSet<notification_recipient> notification_recipient { get; set; }
        public virtual DbSet<notification_replyto> notification_replyto { get; set; }
        public virtual DbSet<notification_sendto> notification_sendto { get; set; }
        public virtual DbSet<notification_trigger> notification_trigger { get; set; }
        public virtual DbSet<engageterm> engageterms { get; set; }
        public virtual DbSet<approver> approvers { get; set; }
        public virtual DbSet<department> departments { get; set; }
        public virtual DbSet<owner_approver> owner_approver { get; set; }
        public virtual DbSet<owner_contact> owner_contact { get; set; }
        public virtual DbSet<owner_department> owner_department { get; set; }
        public virtual DbSet<proxy_approver> proxy_approver { get; set; }
        public virtual DbSet<owner> owners { get; set; }
    }
}
