//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class initiative_type_staffing
    {
        public int initiative_type_staffing_id { get; set; }
        public int initiative_type_id { get; set; }
        public int staffing_id { get; set; }
    
        public virtual initiative_type initiative_type { get; set; }
        public virtual staffing staffing { get; set; }
    }
}
