//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class notification
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public notification()
        {
            this.notification_replyto = new HashSet<notification_replyto>();
            this.notification_sendto = new HashSet<notification_sendto>();
        }
    
        public int notification_id { get; set; }
        public int initiative_type_id { get; set; }
        public int notification_trigger_id { get; set; }
        public string also_send_to { get; set; }
        public string also_reply_to { get; set; }
        public Nullable<int> oldest_year { get; set; }
        public Nullable<int> when_to_send { get; set; }
        public string frm { get; set; }
        public string subject { get; set; }
        public string body { get; set; }
        public string name { get; set; }
    
        public virtual initiative_type initiative_type { get; set; }
        public virtual notification_trigger notification_trigger { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<notification_replyto> notification_replyto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<notification_sendto> notification_sendto { get; set; }
    }
}
