//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class owner_department
    {
        public int owner_department_id { get; set; }
        public int owner_id { get; set; }
        public int department_id { get; set; }
    
        public virtual department department { get; set; }
        public virtual owner owner { get; set; }
    }
}
