//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class proxy_approver
    {
        public int proxy_approver_id { get; set; }
        public int approver_id { get; set; }
        public string name { get; set; }
    
        public virtual approver approver { get; set; }
    }
}
