//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class team_role
    {
        public int team_role_id { get; set; }
        public string name { get; set; }
        public bool legacy { get; set; }
        public bool can_multiple { get; set; }
        public bool mandatory { get; set; }
        public int display_order { get; set; }
    }
}
